### ISSUE TITLE
report-bug-to-drracket-wakatime: '#f' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by crocidb** [racket-tw/drracket-wakatime#3]
After installing it on Windows, setting the api key, every time I open DrRacket, I get this error:

![](https://i.imgur.com/HJJPV5f.png)

```
report-bug-to-drracket-wakatime: '#f' is not recognized as an internal or external command,

operable program or batch file.
```

Any ideas of what that might be?

Thanks!

**Comment by dannypsnl** [comment]
Do you have `wakatime-cli` in the `$PATH`? If you have it in `$PATH`, then you can check [find-executable-path](https://docs.racket-lang.org/reference/Filesystem.html#%28def._%28%28lib._racket%2Fprivate%2Fmisc..rkt%29._find-executable-path%29%29) for further information, since I'm not quite familar with Windows.

**Comment by crocidb** [comment]
Hi @dannypsnl, sorry for the delay. Yes, it was on the PATH variable, however the name of the executable had a typo. The problem is fixed now. :) However, is there a way to improve the error message?

**Comment by dannypsnl** [comment]
Yes, I can add a check to report better message here, thanks for report!
